### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by brauliodiez** [ayosdev/ng-iban-custom#1]
Hello Juven,

 First of all, congratulations, it's a great directive.

 Not sure if I'm missing something, I haven't found unit tests implemented for this directive, in case they haven't been implemented, would you mind if I start implementing them?

 Thanks
   Braulio

**Comment by juvenpajares** [comment]
Hi Braulio,

Appreciate it. A unit test on this directive is a good idea, I'll add you as a collaborator so you can start the implementation. Thanks in advance.

Juven

**Comment by brauliodiez** [comment]
Hi, 

[Pull request added](https://github.com/rs2media/ng-iban-custom/pull/3)

Found Kosovo iban codes not validating (country check has missing kosovo entry), opened an [issue](https://github.com/rs2media/ng-iban-custom/issues/2)

**Comment by juvenpajares** [comment]
@brauliodiez kosovo added
