### ISSUE TITLE
Kosovo Iban failing

### ISSUE THREAD

**Issue by brauliodiez** [ayosdev/ng-iban-custom#2]
Hello,

  Implementing the unit tests I have found that it seems that ngIBan is not working for kosovo:

  Just checked this two values:

 XK051212012345678906
 Source: http://formvalidation.io/validators/iban/

XK051000000000000053
Source: http://www.letterofcredit.biz/Business-Identifier-Code-(BIC)-and-International-Bank-Account-Number-(IBAN).html

Checking in some third parties sites, in some of them I get an ok in some other an error, maybe kosovo has joined recently?

In the ng-iban country I cannot found Kosovo.

**Comment by juvenpajares** [comment]
@brauliodiez added Kosovo
